[package]
name = "verender"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
bytemuck = "1.12.3"
easy-gltf = "0.1.5"
glam = "0.22.0"
rhachis = "0.6"
wgpu = "0.14"
